version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: open-ai-robot
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: pnpm start:prod
